services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: yunami-bot
    image: yunami-bot:${TAG}
    restart: always
    pull_policy: build
    network_mode: host
    environment:
      - DISCORD_TOKEN
      - CLIENT_ID
      - GUILD_ID
      - API_BASE_URL
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: yunami-server
    image: yunami-server:${TAG}
    restart: always
    pull_policy: build
    network_mode: host
    environment:
      - DATABASE_URL
      - NODE_ENV

networks:
  default:
    external: true
    name: host
